name: Update Cloudflare CIDR

on:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上 8 点自动运行
  workflow_dispatch: # 允许你手动点击运行

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch IPv4 CIDR
        run: curl -s https://www.cloudflare.com/ips-v4 -o CF-CIDR.txt

      - name: Fetch IPv6 CIDR (可选)
        run: curl -s https://www.cloudflare.com/ips-v6 -o CF-CIDR-v6.txt

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add CF-CIDR.txt CF-CIDR-v6.txt
          git commit -m "chore: 自动更新 Cloudflare CIDR" || exit 0
          git push
