name: Advanced ASN Classification

on:
  schedule:
    - cron: '0 0 * * 1' # 每周一更新一次即可，ASN 信息变动频率不高
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests ipwhois

      - name: Run ASN Classification
        run: python process_ips.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CF-*.txt
          git commit -m "Update ASN-classified CIDRs" || exit 0
          git push
